#sap连接配置
sap:
  jco:
    provider:
      destName: ABAP
      ashost: 10.1.118.73
      client: 140
      sysnr: 06
      lang: zh
      user: ILAS
      passwd: Tplhk12345
      pool_capacity: 10
      peak_limit: 50
